#ifndef LOG_MARKER_H
#define LOG_MARKER_H

typedef enum {
    LOG_MARKER_DIAGNOSTICS = 0,
    LOG_MARKER_LIFECYCLE = 1,
    LOG_MARKER_INTEGRATION = 2,
    LOG_MARKER_HEALTH = 3,
    LOG_MARKER_TELEMETRY = 4,
    LOG_MARKER_AUDIT_LOG = 5,
    LOG_MARKER_KPI = 6,
    LOG_MARKER_MEASUREMENT = 7
} LogMarker;

#endif /* LOG_MARKER_H */
