#ifndef SIGNAL_OUTPUT_ACTION_H
#define SIGNAL_OUTPUT_ACTION_H

#include <stdint.h>

typedef enum {
    SIGNAL_OUTPUT_ACTION_NONE = 0x0000,
    SIGNAL_OUTPUT_ACTION_EMERGENCY_STOP = 0x0001,
    SIGNAL_OUTPUT_ACTION_IMMEDIATE_STOP = 0x0002,
    SIGNAL_OUTPUT_ACTION_ON_PHASE_STOP = 0x0003,
    SIGNAL_OUTPUT_ACTION_INHIBITION = 0x0004
} SignalOutputAction;

#endif /* SIGNAL_OUTPUT_ACTION_H */
