#ifndef SIGNAL_CATEGORY_H
#define SIGNAL_CATEGORY_H

typedef enum {
    SIGNAL_CATEGORY_ALARM = 0,
    SIGNAL_CATEGORY_ANOMALY = 1,
    SIGNAL_CATEGORY_WARNING = 2,
    SIGNAL_CATEGORY_INFORMATION = 3
} SignalCategory;

#endif /* SIGNAL_CATEGORY_H */
