#ifndef MQTT_PARAMETER_SUB_STATUS_H
#define MQTT_PARAMETER_SUB_STATUS_H

typedef enum {
    MQTT_PARAMETER_SUB_STATUS_IDLE = 0,
    MQTT_PARAMETER_SUB_STATUS_SUBSCRIBE = 1,
    MQTT_PARAMETER_SUB_STATUS_UPDATE_PARAMETERS = 2,
    MQTT_PARAMETER_SUB_STATUS_LISTENING = 3,
    MQTT_PARAMETER_SUB_STATUS_ERROR = 4
} MqttParameterSubStatus;

#endif /* MQTT_PARAMETER_SUB_STATUS_H */
