#ifndef MQTT_PARAMETER_PUB_STATUS_H
#define MQTT_PARAMETER_PUB_STATUS_H

typedef enum {
    MQTT_PARAMETER_PUB_STATUS_IDLE = 0,
    MQTT_PARAMETER_PUB_STATUS_BUILD_JSON = 1,
    MQTT_PARAMETER_PUB_STATUS_SERIALIZE = 2,
    MQTT_PARAMETER_PUB_STATUS_PUBLISH = 3,
    MQTT_PARAMETER_PUB_STATUS_WAIT_ACK = 4
} MqttParameterPubStatus;

#endif /* MQTT_PARAMETER_PUB_STATUS_H */
