#ifndef MAIN_STATUS_H
#define MAIN_STATUS_H

typedef enum {
    MAIN_STATUS_STANDBY,
    MAIN_STATUS_VENTILATION,
    MAIN_STATUS_COOLING,
    MAIN_STATUS_HEATING,
    MAIN_STATUS_DRYING,
    MAIN_STATUS_FAULT
} MainStatus;

#endif // MAIN_STATUS_H
