#ifndef MEAN_FILTER_TYPE_H
#define MEAN_FILTER_TYPE_H

typedef enum {
    MEAN_FILTER_TYPE_SMA = 0,
    MEAN_FILTER_TYPE_WMA_RAMP = 1,
    MEAN_FILTER_TYPE_WMA_TRIANGULAR = 2,
    MEAN_FILTER_TYPE_WMA_TRIANGULAR_ODD_ONLY = 3,
    MEAN_FILTER_TYPE_TRI_SMA2 = 4,
    MEAN_FILTER_TYPE_EMA = 5
} MeanFilterType;

#endif /* MEAN_FILTER_TYPE_H */
