#ifndef WORK_EFFORT_PURPOSE_H
#define WORK_EFFORT_PURPOSE_H

typedef enum {
    WORK_EFFORT_PURPOSE_PRODUCTION = 0,
    WORK_EFFORT_PURPOSE_PROTOTYPE = 1,
    WORK_EFFORT_PURPOSE_TEST = 2,
    WORK_EFFORT_PURPOSE_SAFETY = 3
} WorkEffortPurpose;

#endif /* WORK_EFFORT_PURPOSE_H */
