#ifndef ACTUATOR_TYPE_H
#define ACTUATOR_TYPE_H

typedef enum {
    ACTUATOR_TYPE_ON_OFF,               /* Fallback value */
    ACTUATOR_TYPE_CONTACTOR,
    ACTUATOR_TYPE_SOFT_STARTER,
    ACTUATOR_TYPE_VFD,                  /* Frequency converter / Inverter drive */
    ACTUATOR_TYPE_PNEUMATIC_CYLINDER,
    ACTUATOR_TYPE_PNEUMATIC_VALVE,
    ACTUATOR_TYPE_HYDRAULIC_CYLINDER,
    ACTUATOR_TYPE_HYDRAULIC_VALVE,
    ACTUATOR_TYPE_DAMPER,
    ACTUATOR_TYPE_SOLENOID_VALVE
} ActuatorType;

#endif /* ACTUATOR_TYPE_H */
