#ifndef DEVICE_CONFIG_MGMT_STATUS_H
#define DEVICE_CONFIG_MGMT_STATUS_H

/* Device configuration management FSM states (faithful port of DeviceConfigMgmtStatus.st). */
typedef enum {
    DEVICE_CONFIG_MGMT_IDLE = 0,
    DEVICE_CONFIG_MGMT_INIT,
    DEVICE_CONFIG_MGMT_RESETTING,
    DEVICE_CONFIG_MGMT_CHECK,
    DEVICE_CONFIG_MGMT_LOAD,
    DEVICE_CONFIG_MGMT_WAIT_LOAD,
    DEVICE_CONFIG_MGMT_WAIT_PROCESSING,
    DEVICE_CONFIG_MGMT_INCREMENT_INDEX,
    DEVICE_CONFIG_MGMT_COMPLETED,
    DEVICE_CONFIG_MGMT_ERROR
} DeviceConfigMgmtStatus;

#endif /* DEVICE_CONFIG_MGMT_STATUS_H */
