#ifndef WORK_EFFORT_TYPE_H
#define WORK_EFFORT_TYPE_H

typedef enum {
    WORK_EFFORT_TYPE_REPETITIVE_MANUFACTURING = 0,
    WORK_EFFORT_TYPE_DISCRETE_MANUFACTURING = 1,
    WORK_EFFORT_TYPE_CONTINUOUS_PROCESS = 2,
    WORK_EFFORT_TYPE_BATCH_PROCESS = 3
} WorkEffortType;

#endif /* WORK_EFFORT_TYPE_H */
