#ifndef MQTT_LOG_APPENDER_STATUS_H
#define MQTT_LOG_APPENDER_STATUS_H

typedef enum {
    MQTT_LOG_APPENDER_STATUS_IDLE = 0,
    MQTT_LOG_APPENDER_STATUS_BUILD_JSON = 1,
    MQTT_LOG_APPENDER_STATUS_SERIALIZE = 2,
    MQTT_LOG_APPENDER_STATUS_PUBLISH = 3,
    MQTT_LOG_APPENDER_STATUS_WAIT_ACK = 4
} MqttLogAppenderStatus;

#endif /* MQTT_LOG_APPENDER_STATUS_H */
