#ifndef RESET_POLICY_H
#define RESET_POLICY_H

#include <stdint.h>

typedef enum {
    RESET_POLICY_AUX_RESET = 512,
    RESET_POLICY_UNCONDITIONED_RESET = 16384,
    RESET_POLICY_AUTO_CONDITIONED_RESET = 8192,
    RESET_POLICY_AUTO_PROVISIONAL_RESET = 4096,
    RESET_POLICY_AUTO_PRIORITY_RESET = 2048,
    RESET_POLICY_AUTO_RESET = 1024
} ResetPolicy;

#endif /* RESET_POLICY_H */
