#ifndef SIGNAL_MGMT_OPERATING_MODE_H
#define SIGNAL_MGMT_OPERATING_MODE_H

typedef enum {
    SIGNAL_MGMT_OPERATING_MODE_RESET = 0,
    SIGNAL_MGMT_OPERATING_MODE_PREPARE = 1,
    SIGNAL_MGMT_OPERATING_MODE_PROCESS = 2
} SignalMgmtOperatingMode;

#endif /* SIGNAL_MGMT_OPERATING_MODE_H */
